apiVersion: batch.nai-k8s-ops.com/v1alpha1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: cronjob-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
            containers:
              - name: job-container
                image: busybox
                args:
                  - /bin/sh
                  - -c 
                  - date; echo Hello from the Kubernetes cluster
                securityContext:
                  allowPrivilegeEscalationp: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: false
            restartPolicy: OnFailure
