apiVersion: cache.nai-k8s-ops.com/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: memcached-sample
spec:
  # TODO(user): Add fields here
  # number of Pods/ Instances
  size: 3
