---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-nai-k8s-ops-com-v1alpha1-cronjob
  failurePolicy: Fail
  name: mcronjob-v1alpha1.kb.io
  rules:
  - apiGroups:
    - batch.nai-k8s-ops.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-nai-k8s-ops-com-v1alpha1-cronjob
  failurePolicy: Fail
  name: vcronjob-v1alpha1.kb.io
  rules:
  - apiGroups:
    - batch.nai-k8s-ops.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None
